import test from 'node:test';
import assert from 'node:assert/strict';
import { createEventBus } from './main.js';
test('ordered_payload_and_isolation', () => { const a=createEventBus(),b=createEventBus(),seen=[],payload={id:1};a.on('save',p=>seen.push(['first',p]));a.on('save',p=>seen.push(['second',p]));assert.equal(a.emit('save',payload),2);assert.deepEqual(seen.map(x=>x[0]),['first','second']);assert.ok(seen.every(x=>x[1]===payload));assert.equal(b.emit('save',payload),0);assert.equal(a.listenerCount('missing'),0); });
test('independent_duplicate_subscriptions', () => { const bus=createEventBus();let calls=0;const fn=()=>calls++;const off=bus.on('x',fn);bus.on('x',fn);assert.equal(bus.listenerCount('x'),2);off();off();assert.equal(bus.listenerCount('x'),1);assert.equal(bus.emit('x'),1);assert.equal(calls,1); });
test('snapshot_during_mutation', () => { const bus=createEventBus(),seen=[];let once=true;bus.on('x',()=>{seen.push('a');if(once){once=false;off();bus.on('x',()=>seen.push('c'));}});const off=bus.on('x',()=>seen.push('b'));assert.equal(bus.emit('x'),2);assert.deepEqual(seen,['a','b']);seen.length=0;assert.equal(bus.emit('x'),2);assert.deepEqual(seen,['a','c']); });
test('nested_emit_has_fresh_snapshot', () => { const bus=createEventBus(),seen=[];let nested=false;bus.on('x',()=>{seen.push('a');if(!nested){nested=true;off();assert.equal(bus.emit('x'),1);}});const off=bus.on('x',()=>seen.push('b'));assert.equal(bus.emit('x'),2);assert.deepEqual(seen,['a','a','b']); });
test('exceptions_propagate_and_keep_listeners', () => { const bus=createEventBus(),error=new Error('listener');let later=0;bus.on('x',()=>{throw error;});bus.on('x',()=>later++);assert.throws(()=>bus.emit('x'),e=>e===error);assert.equal(later,0);assert.equal(bus.listenerCount('x'),2); });
test('special_names_and_validation', () => { const bus=createEventBus();bus.on('__proto__',()=>{});assert.equal(bus.emit('__proto__'),1);for(const bad of [null,3,{}]){assert.throws(()=>bus.on(bad,()=>{}),TypeError);assert.throws(()=>bus.emit(bad),TypeError);assert.throws(()=>bus.listenerCount(bad),TypeError);}assert.throws(()=>bus.on('x',null),TypeError); });
